###
// 1 - Returns a list of all states in the state table
GET http://localhost:3000/states/

//Response
# [
#   {
#     stateId: 1,
#     stateName: "Andaman and Nicobar Islands",
#     population: 380581
#   },

#   ...
# ]



###
// 2 - Returns a state based on the state ID
GET http://localhost:3000/states/26/

# Response
# {
#   stateId: 8,
#   stateName: "Delhi",
#   population: 16787941
# }



###
// 3 - Create a district in the district table, district_id is auto-incremented
POST http://localhost:3000/districts/
Content-Type: application/json

{
  "districtName": "Bagalkot",
  "stateId": 3,
  "cases": 2323,
  "cured": 2000,
  "active": 315,
  "deaths": 8
}

# Response
# District Successfully Added


###
// 4 - Returns a district based on the district ID
GET http://localhost:3000/districts/500/

# Response
# {
#   districtId: 322,
#   districtName: "Haveri",
#   stateId: 36,
#   cases: 2816,
#   cured: 2424,
#   active: 172,
#   deaths: 220,
# }



###
// 5 - Deletes a district from the district table based on the district ID
DELETE http://localhost:3000/districts/5/

# Response
# District Remove



###
// 6 - Updates the details of a specific district based on the district ID
PUT http://localhost:3000/districts/10/
Content-Type: application/json

{
  "districtName": "Nadia",
  "stateId": 3,
  "cases": 9628,
  "cured": 6524,
  "active": 3000,
  "deaths": 104
}

# Response
# District Details Up



###
// 7 - Returns the statistics of total cases, cured, active, deaths of a specific state based on state ID
GET http://localhost:3000/states/11/stats/

# Response
# {
#   totalCases: 724355,
#   totalCured: 615324,
#   totalActive: 99254,
#   totalDeaths: 9777
# }



###
// 8 - Returns an object containing the state name of a district based on the district ID
GET http://localhost:3000/districts/100/details/

# Response
# {
#   stateName: "Maharashtra"
# }